package authentication.domain

import kotlinx.datetime.LocalDateTime
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * I have made id and createdAt property nullable with a default null value because they
 * will be autogenerated
 */

@Serializable
data class GeneralUser(
    val id: String? = null,
    @SerialName("created_at")
    val createdAt: LocalDateTime? = null,
    @SerialName("user_name")
    val userName: String,
    val email: String,
    @SerialName("account_type")
    val accountType: AccountType,
)

enum class AccountType {
    GENERAL,
    PROFESSIONAL
}
